import ToastContext from '../components/ToastContext'
import './globals.css'
import SessionContext from '../components/SessionContext'

export const metadata = {
  title: 'Employee Management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionContext>
        <body className="h-[100%] w-full ">{children}
          <ToastContext />
        </body>
      </SessionContext>

    </html>
  )
}
